### ISSUE TITLE
Configuration in example vs. Google Chrome

### ISSUE THREAD

**Issue by tomekkup** [ovea-deprecated/jetty-session-redis#2]
There is an issue with a cookies storing JSESSIONID and Google Chrome. Cookies are not accepted by Chrome when RedisSessionManager is configured with parameteres:

sessionDomain - localhost
sessionPath -/
maxCookieAge - 86400
refreshCookieAge - 300

Probably maxCookieAge is wrong but I tried with several values (f.e. -1, max) without success.

**Comment by mathieucarbou** [comment]
weird... The RedisSessionManager does not handle at all cookies: it only deals with sessions. The parameters you set are used on the Jetty's superclass.

**Comment by tomekkup** [comment]
correct.
